### ISSUE TITLE
Installation error width database key error

### ISSUE THREAD

**Issue by aw73** [sunlix/ProcessAbbreviate#2]
On Processwire 3.0.61 and PHP 7.1.4 I have this error on module install

`SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`
`Failed to init module: Abbreviate - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tool_processwire.abbreviations' doesn't exist`

**Comment by sunlix** [comment]
Hi, on what encoding runs your installation? utf8 or newer utf8mb4?
I think it is utf8mb4 - I will have a look.

**Comment by besens** [comment]
Then I just replaced title varchar(191) from varchar(255)...

Then the database table is ok... But I got this error when I go to the Abbreviations management :

`Class 'ProcessWire\Abbreviation' not found in /home/srufer/public_html/tool_processwire/site/modules/Abbreviate/ProcessAbbreviate.module:155`

**Comment by aw73** [comment]
Yes I used MariaDB and I have to configure it in utf8mb4. varchar(191) is a good alternative ;-)

**Comment by sunlix** [comment]
thanks, i will submit a patch.

proesswire offers a [special method](https://github.com/processwire/processwire/blob/master/wire/core/WireDatabasePDO.php#L788-L799) to got the needed info.
